/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Dtrujillo
 */
public class CalculadoraDerivada extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraDerivada
     */
    public CalculadoraDerivada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFunction = new javax.swing.JTextField();
        txtFuncionSalida = new javax.swing.JTextField();
        btnDerivar = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        brtmenos = new javax.swing.JButton();
        btnmas = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnelev = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btnparen1 = new javax.swing.JButton();
        btnparen2 = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnpi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Funcion A derivar:");

        jLabel2.setText("Funcion derivada:");

        txtFuncionSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionSalidaActionPerformed(evt);
            }
        });

        btnDerivar.setText("Derivar");
        btnDerivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivarActionPerformed(evt);
            }
        });

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7number_7_3074.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-7-icon_34776.png"))); // NOI18N
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-7-icon_34776.png"))); // NOI18N

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8number_8_3824.png"))); // NOI18N
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-8-icon_34775.png"))); // NOI18N
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-8-icon_34775.png"))); // NOI18N

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9number_9_3071.png"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-9-icon_34774.png"))); // NOI18N
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-9-icon_34774.png"))); // NOI18N

        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btndel.setBorderPainted(false);
        btndel.setContentAreaFilled(false);
        btndel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elim.png"))); // NOI18N
        btndel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elim.png"))); // NOI18N

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4number_4_3829 (1).png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-4-icon_34779.png"))); // NOI18N
        btn4.setRequestFocusEnabled(false);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-4-icon_34779.png"))); // NOI18N

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_number_3827.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-5-icon_34778.png"))); // NOI18N
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-5-icon_34778.png"))); // NOI18N

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6_number_3075.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-6-icon_34777.png"))); // NOI18N
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-6-icon_34777.png"))); // NOI18N

        btnx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.setBorderPainted(false);
        btnx.setContentAreaFilled(false);
        btnx.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N

        btndiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/division_box_icon_137684.png"))); // NOI18N
        btndiv.setBorderPainted(false);
        btndiv.setContentAreaFilled(false);
        btndiv.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486505258-divide-division-dote-square_81435.png"))); // NOI18N
        btndiv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486505258-divide-division-dote-square_81435.png"))); // NOI18N

        brtmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minus-gross-horizontal-straight-line-symbol_icon-icons.com_74137.png"))); // NOI18N
        brtmenos.setToolTipText("");
        brtmenos.setBorderPainted(false);
        brtmenos.setContentAreaFilled(false);
        brtmenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486504817-delete-minus-cancel-exit-remove_81373.png"))); // NOI18N
        brtmenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486504817-delete-minus-cancel-exit-remove_81373.png"))); // NOI18N

        btnmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_icon-icons.com_74429.png"))); // NOI18N
        btnmas.setBorderPainted(false);
        btnmas.setContentAreaFilled(false);
        btnmas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus_40632.png"))); // NOI18N
        btnmas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus_40632.png"))); // NOI18N

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2number_2_3079 (1).png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-2-icon_34781 (1).png"))); // NOI18N
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-2-icon_34781 (1).png"))); // NOI18N

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3number_3_3077 (1).png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-3-icon_34780 (1).png"))); // NOI18N
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-3-icon_34780 (1).png"))); // NOI18N

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1number_1_3831 (1).png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-1-icon_34782 (1).png"))); // NOI18N
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-1-icon_34782 (1).png"))); // NOI18N

        btnpunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N
        btnpunto.setBorderPainted(false);
        btnpunto.setContentAreaFilled(false);
        btnpunto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N
        btnpunto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N

        btncos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.setBorderPainted(false);
        btncos.setContentAreaFilled(false);
        btncos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N

        btnsin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.setBorderPainted(false);
        btnsin.setContentAreaFilled(false);
        btnsin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N

        btnigual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.setToolTipText("");
        btnigual.setBorderPainted(false);
        btnigual.setContentAreaFilled(false);
        btnigual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N

        btntan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.setBorderPainted(false);
        btntan.setContentAreaFilled(false);
        btntan.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N

        btnelev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.setBorderPainted(false);
        btnelev.setContentAreaFilled(false);
        btnelev.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N

        btnraiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.setBorderPainted(false);
        btnraiz.setContentAreaFilled(false);
        btnraiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N

        btnparen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen1.setBorderPainted(false);
        btnparen1.setContentAreaFilled(false);
        btnparen1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N

        btnparen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen2.setBorderPainted(false);
        btnparen2.setContentAreaFilled(false);
        btnparen2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N

        btnlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_log_icon_135415.png"))); // NOI18N
        btnlog.setBorderPainted(false);
        btnlog.setContentAreaFilled(false);
        btnlog.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_29907.png"))); // NOI18N
        btnlog.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_29907.png"))); // NOI18N

        btnpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.setBorderPainted(false);
        btnpi.setContentAreaFilled(false);
        btnpi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnDerivar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btncos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnigual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnelev)
                                .addGap(2, 2, 2)
                                .addComponent(btnraiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntan)))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtFuncionSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brtmenos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndiv))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpunto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsin))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnparen1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnparen2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnlog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpi)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btndel)
                    .addComponent(btnC))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btnx)
                    .addComponent(btndiv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2)
                        .addComponent(btn3)
                        .addComponent(btnmas)
                        .addComponent(brtmenos))
                    .addComponent(btn1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFuncionSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpunto)
                            .addComponent(btn0)
                            .addComponent(btnsin)
                            .addComponent(btncos)
                            .addComponent(btnigual))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnDerivar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnparen2)
                            .addComponent(btnparen1)
                            .addComponent(btnelev)
                            .addComponent(btnraiz)
                            .addComponent(btntan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlog)
                    .addComponent(btnpi))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncionSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncionSalidaActionPerformed

    private void btnDerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivarActionPerformed
        String funcion = txtFunction.getText();
        Derivadas derivada = new Derivadas();
        derivada.setFuncionADerivar(funcion);
        derivada.derivar();
        txtFuncionSalida.setText(derivada.getFuncionDerivada());
        
    }//GEN-LAST:event_btnDerivarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraDerivada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtmenos;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDerivar;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnelev;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmas;
    private javax.swing.JButton btnparen1;
    private javax.swing.JButton btnparen2;
    private javax.swing.JButton btnpi;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFuncionSalida;
    private javax.swing.JTextField txtFunction;
    // End of variables declaration//GEN-END:variables
}
