/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Dtrujillo
 */
public class CalculadoraDerivada extends javax.swing.JFrame {
    /**
     * Creates new form CalculadoraDerivada
     */
    private boolean punto=true; //sirve para el punto
    String valor1, valor2, signo, contenido;
    Double resultado;
    
    public CalculadoraDerivada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFunction = new javax.swing.JTextField();
        txtFuncionSalida = new javax.swing.JTextField();
        btnDerivar = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        brtmenos = new javax.swing.JButton();
        btnmas = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnelev = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btnparen1 = new javax.swing.JButton();
        btnparen2 = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnpi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setText("Funcion A derivar:");

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel2.setText("Funcion derivada:");

        txtFunction.setBackground(new java.awt.Color(0, 0, 0));
        txtFunction.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        txtFunction.setForeground(new java.awt.Color(51, 255, 51));
        txtFunction.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtFuncionSalida.setBackground(new java.awt.Color(0, 0, 0));
        txtFuncionSalida.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        txtFuncionSalida.setForeground(new java.awt.Color(0, 255, 51));
        txtFuncionSalida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFuncionSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionSalidaActionPerformed(evt);
            }
        });

        btnDerivar.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        btnDerivar.setText("Derivar");
        btnDerivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivarActionPerformed(evt);
            }
        });

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7number_7_3074.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-7-icon_34776.png"))); // NOI18N
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-7-icon_34776.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8number_8_3824.png"))); // NOI18N
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-8-icon_34775.png"))); // NOI18N
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-8-icon_34775.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9number_9_3071.png"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-9-icon_34774.png"))); // NOI18N
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-9-icon_34774.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btndel.setBorderPainted(false);
        btndel.setContentAreaFilled(false);
        btndel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elim.png"))); // NOI18N
        btndel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/elim.png"))); // NOI18N
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4number_4_3829 (1).png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-4-icon_34779.png"))); // NOI18N
        btn4.setRequestFocusEnabled(false);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-4-icon_34779.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter-C-icon_34763.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5_number_3827.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-5-icon_34778.png"))); // NOI18N
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-5-icon_34778.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6_number_3075.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-6-icon_34777.png"))); // NOI18N
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-6-icon_34777.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.setBorderPainted(false);
        btnx.setContentAreaFilled(false);
        btnx.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication_box_icon_138361.png"))); // NOI18N
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });

        btndiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/division_box_icon_137684.png"))); // NOI18N
        btndiv.setBorderPainted(false);
        btndiv.setContentAreaFilled(false);
        btndiv.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486505258-divide-division-dote-square_81435.png"))); // NOI18N
        btndiv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486505258-divide-division-dote-square_81435.png"))); // NOI18N
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        brtmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minus-gross-horizontal-straight-line-symbol_icon-icons.com_74137.png"))); // NOI18N
        brtmenos.setToolTipText("");
        brtmenos.setBorderPainted(false);
        brtmenos.setContentAreaFilled(false);
        brtmenos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486504817-delete-minus-cancel-exit-remove_81373.png"))); // NOI18N
        brtmenos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486504817-delete-minus-cancel-exit-remove_81373.png"))); // NOI18N
        brtmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtmenosActionPerformed(evt);
            }
        });

        btnmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_icon-icons.com_74429.png"))); // NOI18N
        btnmas.setBorderPainted(false);
        btnmas.setContentAreaFilled(false);
        btnmas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus_40632.png"))); // NOI18N
        btnmas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus_40632.png"))); // NOI18N
        btnmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasActionPerformed(evt);
            }
        });

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2number_2_3079 (1).png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-2-icon_34781 (1).png"))); // NOI18N
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-2-icon_34781 (1).png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3number_3_3077 (1).png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-3-icon_34780 (1).png"))); // NOI18N
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-3-icon_34780 (1).png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1number_1_3831 (1).png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-1-icon_34782 (1).png"))); // NOI18N
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Number-1-icon_34782 (1).png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnpunto.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnpunto.setText(".");
        btnpunto.setBorderPainted(false);
        btnpunto.setContentAreaFilled(false);
        btnpunto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N
        btnpunto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/point_icon_151143.png"))); // NOI18N
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/number_square_zero_icon_173664.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btncos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.setBorderPainted(false);
        btncos.setContentAreaFilled(false);
        btncos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_cos_icon_135417.png"))); // NOI18N
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });

        btnsin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.setBorderPainted(false);
        btnsin.setContentAreaFilled(false);
        btnsin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_sin_icon_137417.png"))); // NOI18N
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });

        btnigual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.setToolTipText("");
        btnigual.setBorderPainted(false);
        btnigual.setContentAreaFilled(false);
        btnigual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_equals_icon_158292.png"))); // NOI18N
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });

        btntan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.setBorderPainted(false);
        btntan.setContentAreaFilled(false);
        btntan.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_tan_icon_138395.png"))); // NOI18N
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });

        btnelev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.setBorderPainted(false);
        btnelev.setContentAreaFilled(false);
        btnelev.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exponent_box_icon_136652.png"))); // NOI18N
        btnelev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelevActionPerformed(evt);
            }
        });

        btnraiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.setBorderPainted(false);
        btnraiz.setContentAreaFilled(false);
        btnraiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/squareroot_cuadrad_3927.png"))); // NOI18N
        btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizActionPerformed(evt);
            }
        });

        btnparen1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnparen1.setText("(");
        btnparen1.setToolTipText("");
        btnparen1.setBorderPainted(false);
        btnparen1.setContentAreaFilled(false);
        btnparen1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparen1ActionPerformed(evt);
            }
        });

        btnparen2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnparen2.setText(")");
        btnparen2.setBorderPainted(false);
        btnparen2.setContentAreaFilled(false);
        btnparen2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parentheses_icon_151165.png"))); // NOI18N
        btnparen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparen2ActionPerformed(evt);
            }
        });

        btnlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/math_log_icon_135415.png"))); // NOI18N
        btnlog.setBorderPainted(false);
        btnlog.setContentAreaFilled(false);
        btnlog.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_29907.png"))); // NOI18N
        btnlog.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log_29907.png"))); // NOI18N
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        btnpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.setBorderPainted(false);
        btnpi.setContentAreaFilled(false);
        btnpi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pi_box_icon_135306.png"))); // NOI18N
        btnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpiActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton1.setText("+/-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel5.setText("Ejemplos:");

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel6.setText("Derivada Logaritmica");

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel7.setText("Derivada Exponencial");

        jButton2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton2.setText("f(x) = e^x-x");
        jButton2.setActionCommand("f'(x) = e^x-x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton3.setText("f(x) = log (3x^2-2x+1)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(89, 89, 89)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jLabel6)
                    .addContainerGap(453, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(307, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(206, 206, 206)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnx)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btndiv)
                                .addComponent(btnelev)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn8)
                            .addGap(8, 8, 8)
                            .addComponent(btn9)
                            .addGap(18, 18, 18)
                            .addComponent(btnpi))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnigual)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn1)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn3)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn0)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnraiz)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnmas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(brtmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btnDerivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(12, 12, 12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnparen1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnparen2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnC))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFuncionSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFunction))
                        .addGap(4, 4, 4)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncionSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnparen2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnparen1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnpunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnC)
                                    .addComponent(btndel))
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnsin)
                                .addComponent(btncos)
                                .addComponent(btntan)
                                .addComponent(btnlog)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnelev)
                                    .addComponent(btnpi))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn8)
                                    .addComponent(btn7)
                                    .addComponent(btn9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6)
                            .addComponent(btndiv)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn5)
                                .addComponent(btnx))
                            .addComponent(btn4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnmas)
                                            .addComponent(brtmenos)))
                                    .addComponent(btn1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnigual))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDerivar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnraiz)
                                    .addComponent(btn0)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuncionSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncionSalidaActionPerformed

    private void btnDerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivarActionPerformed
        String funcion = txtFunction.getText();
        Derivadas derivada = new Derivadas();
        derivada.setFuncionADerivar(funcion);
        derivada.derivar();
        txtFuncionSalida.setText(derivada.getFuncionDerivada());
        
    }//GEN-LAST:event_btnDerivarActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
       txtFunction.setText(txtFunction.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnelevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelevActionPerformed
    txtFunction.setText(txtFunction.getText()+"^");
// TODO add your handling code here:
    }//GEN-LAST:event_btnelevActionPerformed

    private void btnmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasActionPerformed
       txtFunction.setText(txtFunction.getText()+"+");
    }//GEN-LAST:event_btnmasActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtFunction.setText(txtFunction.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
       contenido=txtFunction.getText();
       //contenido menor o igual a 0, muestra "o"
       //si el campo está vacio muestra "0."
       if(contenido.length()<=0){
            txtFunction.setText("0.");
       } else
           //contamos cuantos puntos existen, si existe un punto,
           //no podra colocarse otro punto
           if(txtFunction.getText().contains(".")){
           }else{
                       txtFunction.setText(txtFunction.getText()+".");
                       punto=false;
                       
           }
    }//GEN-LAST:event_btnpuntoActionPerformed
        
    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        txtFunction.setText(txtFunction.getText()+"sin");
    }//GEN-LAST:event_btnsinActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        txtFunction.setText(txtFunction.getText()+"cos");
    }//GEN-LAST:event_btncosActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        txtFunction.setText(txtFunction.getText()+"=");
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnparen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparen1ActionPerformed
       txtFunction.setText(txtFunction.getText()+"(");
    }//GEN-LAST:event_btnparen1ActionPerformed

    private void btnparen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparen2ActionPerformed
       txtFunction.setText(txtFunction.getText()+")");
    }//GEN-LAST:event_btnparen2ActionPerformed

    private void btnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizActionPerformed
        txtFunction.setText(txtFunction.getText()+"sqrt(");
    }//GEN-LAST:event_btnraizActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
         txtFunction.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      txtFunction.setText(txtFunction.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        txtFunction.setText(txtFunction.getText()+"tan");
    }//GEN-LAST:event_btntanActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        txtFunction.setText(txtFunction.getText()+"log");
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpiActionPerformed
        txtFunction.setText(txtFunction.getText()+"3.1416");
    }//GEN-LAST:event_btnpiActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       txtFunction.setText(txtFunction.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtFunction.setText(txtFunction.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void brtmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtmenosActionPerformed
       txtFunction.setText(txtFunction.getText()+"-");
    }//GEN-LAST:event_brtmenosActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
      txtFunction.setText(txtFunction.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       txtFunction.setText(txtFunction.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtFunction.setText(txtFunction.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
       txtFunction.setText(txtFunction.getText()+"*");
    }//GEN-LAST:event_btnxActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        txtFunction.setText(txtFunction.getText()+"/");
    }//GEN-LAST:event_btndivActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
      txtFunction.setText(txtFunction.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtFunction.setText(txtFunction.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     contenido=txtFunction.getText();
     if(contenido.length()>0){
       resultado=(-1)*Double.parseDouble(contenido); 
       txtFunction.setText(resultado.toString());
       //Multiplicamoes el -1 para convertir un numero a positivo o negativo
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
       
        //Boton borrar
        contenido=txtFunction.getText();
        if(contenido.length()>0){
            contenido = contenido.substring(0,contenido.length()-1);
            txtFunction.setText(contenido);
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtFunction.setText("e^x-x");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtFunction.setText("log(3x^2-2x+1)");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDerivada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraDerivada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtmenos;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDerivar;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnelev;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmas;
    private javax.swing.JButton btnparen1;
    private javax.swing.JButton btnparen2;
    private javax.swing.JButton btnpi;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFuncionSalida;
    private javax.swing.JTextField txtFunction;
    // End of variables declaration//GEN-END:variables
}
